### ISSUE TITLE
Hello, could you please provide the code before packaging？

### ISSUE THREAD

**Issue by EzrealPrince** [Dan-Banfield/Lua-Code-Editor#1]
Like the title

**Comment by Dan-Banfield** [comment]
Hi! The code in this repository isn't packaged, it's inside the .js files. As it's written in JavaScript, it does not need to be compiled.

**Comment by Dan-Banfield** [comment]
> Like the title

Hi! The code in this repository isn't packaged, it's inside the .js files. As it's written in JavaScript, it does not need to be compiled.
